### ISSUE TITLE
User Logout

### ISSUE THREAD

**Issue by Nesschen** [psit4-lamas/PSIT4-LaMaS#28]
As an administrator/tutor/student, I want to be able to log out, so that I can leave the page.

**Acceptance criteria**:
- [ ] the user gets logged out

Task:
- [ ] create redux (actions/reducers) method to request a user logout
- [ ] add a Logout button on TopMenu component

**Comment by aleksandar-spasojevic** [comment]
The way circleCI is executing the nightwatch - selenium tests is strange, see for example two repetitive test calls, just seconds between them:

![circleCIReptetitiveTestCalls.jpeg](https://images.zenhubusercontent.com/5c74289430549e587564e442/4ae9544c-96c9-4392-8939-a441be68f34f)

Something is happening, either on OS or the browser itself (maybe in conjunction with selenium). I suggest we ask someone else who has experience with circleCI and nightwatch+selenium with newest geckodriver and chromedriver, because right now I have no clue where to look - since the behavior is not deterministic.
